usage:
	echo "read directions"
encode:
	@python vigenere.py encode $(ARGS)
decode:
	@python vigenere.py decode $(ARGS)
crack:
	@python vigenere.py crack $(ARGS)
getkey:
	@python vigenere.py getkey $(ARGS)
