test: rolling.mdl main.py matrix.py mdl.py display.py draw.py gmath.py mesh_parser.py
	python main.py spinning.mdl

clean:
	rm -f *pyc
	rm -f *out
	rm -f parsetab.py
	rm -f *~
	rm -f *.png
	rm -f *.ppm
	rm -rf __pycache__
	rm -rf ply/__pycache__
	rm -f anim/*.png
